//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BizTalkLibrary.WS_CustomerContact {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CustomerContact_Binding", Namespace="urn:microsoft-dynamics-schemas/page/customercontact")]
    public partial class CustomerContact_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadByRecIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsUpdatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecIdFromKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CustomerContact_Service() {
            this.Url = global::BizTalkLibrary.Properties.Settings.Default.BizTalkLibrary_CustomerCard_CustomerContact_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReadCompletedEventHandler ReadCompleted;
        
        /// <remarks/>
        public event ReadByRecIdCompletedEventHandler ReadByRecIdCompleted;
        
        /// <remarks/>
        public event ReadMultipleCompletedEventHandler ReadMultipleCompleted;
        
        /// <remarks/>
        public event IsUpdatedCompletedEventHandler IsUpdatedCompleted;
        
        /// <remarks/>
        public event GetRecIdFromKeyCompletedEventHandler GetRecIdFromKeyCompleted;
        
        /// <remarks/>
        public event CreateCompletedEventHandler CreateCompleted;
        
        /// <remarks/>
        public event CreateMultipleCompletedEventHandler CreateMultipleCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event UpdateMultipleCompletedEventHandler UpdateMultipleCompleted;
        
        /// <remarks/>
        public event DeleteCompletedEventHandler DeleteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/customercontact:Read", RequestNamespace="urn:microsoft-dynamics-schemas/page/customercontact", ResponseElementName="Read_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/customercontact", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("CustomerContact")]
        public CustomerContact Read(string Sell_to_Customer_No, int Contact_ID) {
            object[] results = this.Invoke("Read", new object[] {
                        Sell_to_Customer_No,
                        Contact_ID});
            return ((CustomerContact)(results[0]));
        }
        
        /// <remarks/>
        public void ReadAsync(string Sell_to_Customer_No, int Contact_ID) {
            this.ReadAsync(Sell_to_Customer_No, Contact_ID, null);
        }
        
        /// <remarks/>
        public void ReadAsync(string Sell_to_Customer_No, int Contact_ID, object userState) {
            if ((this.ReadOperationCompleted == null)) {
                this.ReadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadOperationCompleted);
            }
            this.InvokeAsync("Read", new object[] {
                        Sell_to_Customer_No,
                        Contact_ID}, this.ReadOperationCompleted, userState);
        }
        
        private void OnReadOperationCompleted(object arg) {
            if ((this.ReadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadCompleted(this, new ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/customercontact:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/customercontact", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/customercontact", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("CustomerContact")]
        public CustomerContact ReadByRecId(string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        recId});
            return ((CustomerContact)(results[0]));
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId) {
            this.ReadByRecIdAsync(recId, null);
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId, object userState) {
            if ((this.ReadByRecIdOperationCompleted == null)) {
                this.ReadByRecIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadByRecIdOperationCompleted);
            }
            this.InvokeAsync("ReadByRecId", new object[] {
                        recId}, this.ReadByRecIdOperationCompleted, userState);
        }
        
        private void OnReadByRecIdOperationCompleted(object arg) {
            if ((this.ReadByRecIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadByRecIdCompleted(this, new ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/customercontact:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/customercontact", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/customercontact", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public CustomerContact[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] CustomerContact_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((CustomerContact[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(CustomerContact_Filter[] filter, string bookmarkKey, int setSize) {
            this.ReadMultipleAsync(filter, bookmarkKey, setSize, null);
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(CustomerContact_Filter[] filter, string bookmarkKey, int setSize, object userState) {
            if ((this.ReadMultipleOperationCompleted == null)) {
                this.ReadMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadMultipleOperationCompleted);
            }
            this.InvokeAsync("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, this.ReadMultipleOperationCompleted, userState);
        }
        
        private void OnReadMultipleOperationCompleted(object arg) {
            if ((this.ReadMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadMultipleCompleted(this, new ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/customercontact:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/customercontact", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/customercontact", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key) {
            this.IsUpdatedAsync(Key, null);
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key, object userState) {
            if ((this.IsUpdatedOperationCompleted == null)) {
                this.IsUpdatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUpdatedOperationCompleted);
            }
            this.InvokeAsync("IsUpdated", new object[] {
                        Key}, this.IsUpdatedOperationCompleted, userState);
        }
        
        private void OnIsUpdatedOperationCompleted(object arg) {
            if ((this.IsUpdatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUpdatedCompleted(this, new IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/customercontact:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/customercontact", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/customercontact", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key) {
            this.GetRecIdFromKeyAsync(Key, null);
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key, object userState) {
            if ((this.GetRecIdFromKeyOperationCompleted == null)) {
                this.GetRecIdFromKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecIdFromKeyOperationCompleted);
            }
            this.InvokeAsync("GetRecIdFromKey", new object[] {
                        Key}, this.GetRecIdFromKeyOperationCompleted, userState);
        }
        
        private void OnGetRecIdFromKeyOperationCompleted(object arg) {
            if ((this.GetRecIdFromKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecIdFromKeyCompleted(this, new GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/customercontact:Create", RequestNamespace="urn:microsoft-dynamics-schemas/page/customercontact", ResponseElementName="Create_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/customercontact", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Create(ref CustomerContact CustomerContact) {
            object[] results = this.Invoke("Create", new object[] {
                        CustomerContact});
            CustomerContact = ((CustomerContact)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAsync(CustomerContact CustomerContact) {
            this.CreateAsync(CustomerContact, null);
        }
        
        /// <remarks/>
        public void CreateAsync(CustomerContact CustomerContact, object userState) {
            if ((this.CreateOperationCompleted == null)) {
                this.CreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOperationCompleted);
            }
            this.InvokeAsync("Create", new object[] {
                        CustomerContact}, this.CreateOperationCompleted, userState);
        }
        
        private void OnCreateOperationCompleted(object arg) {
            if ((this.CreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCompleted(this, new CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/customercontact:CreateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/customercontact", ResponseElementName="CreateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/customercontact", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref CustomerContact[] CustomerContact_List) {
            object[] results = this.Invoke("CreateMultiple", new object[] {
                        CustomerContact_List});
            CustomerContact_List = ((CustomerContact[])(results[0]));
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(CustomerContact[] CustomerContact_List) {
            this.CreateMultipleAsync(CustomerContact_List, null);
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(CustomerContact[] CustomerContact_List, object userState) {
            if ((this.CreateMultipleOperationCompleted == null)) {
                this.CreateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateMultipleOperationCompleted);
            }
            this.InvokeAsync("CreateMultiple", new object[] {
                        CustomerContact_List}, this.CreateMultipleOperationCompleted, userState);
        }
        
        private void OnCreateMultipleOperationCompleted(object arg) {
            if ((this.CreateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateMultipleCompleted(this, new CreateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/customercontact:Update", RequestNamespace="urn:microsoft-dynamics-schemas/page/customercontact", ResponseElementName="Update_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/customercontact", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(ref CustomerContact CustomerContact) {
            object[] results = this.Invoke("Update", new object[] {
                        CustomerContact});
            CustomerContact = ((CustomerContact)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(CustomerContact CustomerContact) {
            this.UpdateAsync(CustomerContact, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(CustomerContact CustomerContact, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        CustomerContact}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/customercontact:UpdateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/customercontact", ResponseElementName="UpdateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/customercontact", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref CustomerContact[] CustomerContact_List) {
            object[] results = this.Invoke("UpdateMultiple", new object[] {
                        CustomerContact_List});
            CustomerContact_List = ((CustomerContact[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(CustomerContact[] CustomerContact_List) {
            this.UpdateMultipleAsync(CustomerContact_List, null);
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(CustomerContact[] CustomerContact_List, object userState) {
            if ((this.UpdateMultipleOperationCompleted == null)) {
                this.UpdateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMultipleOperationCompleted);
            }
            this.InvokeAsync("UpdateMultiple", new object[] {
                        CustomerContact_List}, this.UpdateMultipleOperationCompleted, userState);
        }
        
        private void OnUpdateMultipleOperationCompleted(object arg) {
            if ((this.UpdateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMultipleCompleted(this, new UpdateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/customercontact:Delete", RequestNamespace="urn:microsoft-dynamics-schemas/page/customercontact", ResponseElementName="Delete_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/customercontact", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Result")]
        public bool Delete(string Key) {
            object[] results = this.Invoke("Delete", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAsync(string Key) {
            this.DeleteAsync(Key, null);
        }
        
        /// <remarks/>
        public void DeleteAsync(string Key, object userState) {
            if ((this.DeleteOperationCompleted == null)) {
                this.DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOperationCompleted);
            }
            this.InvokeAsync("Delete", new object[] {
                        Key}, this.DeleteOperationCompleted, userState);
        }
        
        private void OnDeleteOperationCompleted(object arg) {
            if ((this.DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customercontact")]
    public partial class CustomerContact {
        
        private string keyField;
        
        private string sell_to_Customer_NoField;
        
        private int contact_IDField;
        
        private bool contact_IDFieldSpecified;
        
        private string prefixField;
        
        private string first_NameField;
        
        private string middle_NameField;
        
        private string last_NameField;
        
        private string suffixField;
        
        private string contact_NameField;
        
        private string calendarsField;
        
        private bool unsubscribeField;
        
        private bool unsubscribeFieldSpecified;
        
        private bool con_SentField;
        
        private bool con_SentFieldSpecified;
        
        private Marketing_Pref marketing_PrefField;
        
        private bool marketing_PrefFieldSpecified;
        
        private Item1234 item1234Field;
        
        private bool item1234FieldSpecified;
        
        private string buildingField;
        
        private string roomField;
        
        private string uS_Area_CodeField;
        
        private string phone_PrefixField;
        
        private string numberField;
        
        private string extensionField;
        
        private string international_Phone_NumberField;
        
        private string fAX_Area_CodeField;
        
        private string fAX_PrefixField;
        
        private string fAX_NumberField;
        
        private Title titleField;
        
        private bool titleFieldSpecified;
        
        private Lab_Type lab_TypeField;
        
        private bool lab_TypeFieldSpecified;
        
        private Discipline disciplineField;
        
        private bool disciplineFieldSpecified;
        
        private string contact_E_MailField;
        
        private string contact_CommentsField;
        
        private string notesField;
        
        private string mKTG_AddressField;
        
        private string cityField;
        
        private string stateField;
        
        private string zipField;
        
        private string contact_PhoneField;
        
        private string contact_FaxField;
        
        private string colorField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Sell_to_Customer_No {
            get {
                return this.sell_to_Customer_NoField;
            }
            set {
                this.sell_to_Customer_NoField = value;
            }
        }
        
        /// <remarks/>
        public int Contact_ID {
            get {
                return this.contact_IDField;
            }
            set {
                this.contact_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Contact_IDSpecified {
            get {
                return this.contact_IDFieldSpecified;
            }
            set {
                this.contact_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Prefix {
            get {
                return this.prefixField;
            }
            set {
                this.prefixField = value;
            }
        }
        
        /// <remarks/>
        public string First_Name {
            get {
                return this.first_NameField;
            }
            set {
                this.first_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Middle_Name {
            get {
                return this.middle_NameField;
            }
            set {
                this.middle_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Last_Name {
            get {
                return this.last_NameField;
            }
            set {
                this.last_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Suffix {
            get {
                return this.suffixField;
            }
            set {
                this.suffixField = value;
            }
        }
        
        /// <remarks/>
        public string Contact_Name {
            get {
                return this.contact_NameField;
            }
            set {
                this.contact_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Calendars {
            get {
                return this.calendarsField;
            }
            set {
                this.calendarsField = value;
            }
        }
        
        /// <remarks/>
        public bool Unsubscribe {
            get {
                return this.unsubscribeField;
            }
            set {
                this.unsubscribeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UnsubscribeSpecified {
            get {
                return this.unsubscribeFieldSpecified;
            }
            set {
                this.unsubscribeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Con_Sent {
            get {
                return this.con_SentField;
            }
            set {
                this.con_SentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Con_SentSpecified {
            get {
                return this.con_SentFieldSpecified;
            }
            set {
                this.con_SentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Marketing_Pref Marketing_Pref {
            get {
                return this.marketing_PrefField;
            }
            set {
                this.marketing_PrefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Marketing_PrefSpecified {
            get {
                return this.marketing_PrefFieldSpecified;
            }
            set {
                this.marketing_PrefFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("1234")]
        public Item1234 Item1234 {
            get {
                return this.item1234Field;
            }
            set {
                this.item1234Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Item1234Specified {
            get {
                return this.item1234FieldSpecified;
            }
            set {
                this.item1234FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Building {
            get {
                return this.buildingField;
            }
            set {
                this.buildingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Room#")]
        public string Room {
            get {
                return this.roomField;
            }
            set {
                this.roomField = value;
            }
        }
        
        /// <remarks/>
        public string US_Area_Code {
            get {
                return this.uS_Area_CodeField;
            }
            set {
                this.uS_Area_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Phone_Prefix {
            get {
                return this.phone_PrefixField;
            }
            set {
                this.phone_PrefixField = value;
            }
        }
        
        /// <remarks/>
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public string Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        public string International_Phone_Number {
            get {
                return this.international_Phone_NumberField;
            }
            set {
                this.international_Phone_NumberField = value;
            }
        }
        
        /// <remarks/>
        public string FAX_Area_Code {
            get {
                return this.fAX_Area_CodeField;
            }
            set {
                this.fAX_Area_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string FAX_Prefix {
            get {
                return this.fAX_PrefixField;
            }
            set {
                this.fAX_PrefixField = value;
            }
        }
        
        /// <remarks/>
        public string FAX_Number {
            get {
                return this.fAX_NumberField;
            }
            set {
                this.fAX_NumberField = value;
            }
        }
        
        /// <remarks/>
        public Title Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TitleSpecified {
            get {
                return this.titleFieldSpecified;
            }
            set {
                this.titleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Lab_Type Lab_Type {
            get {
                return this.lab_TypeField;
            }
            set {
                this.lab_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Lab_TypeSpecified {
            get {
                return this.lab_TypeFieldSpecified;
            }
            set {
                this.lab_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Discipline Discipline {
            get {
                return this.disciplineField;
            }
            set {
                this.disciplineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DisciplineSpecified {
            get {
                return this.disciplineFieldSpecified;
            }
            set {
                this.disciplineFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Contact_E_Mail {
            get {
                return this.contact_E_MailField;
            }
            set {
                this.contact_E_MailField = value;
            }
        }
        
        /// <remarks/>
        public string Contact_Comments {
            get {
                return this.contact_CommentsField;
            }
            set {
                this.contact_CommentsField = value;
            }
        }
        
        /// <remarks/>
        public string Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        public string MKTG_Address {
            get {
                return this.mKTG_AddressField;
            }
            set {
                this.mKTG_AddressField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        public string Contact_Phone {
            get {
                return this.contact_PhoneField;
            }
            set {
                this.contact_PhoneField = value;
            }
        }
        
        /// <remarks/>
        public string Contact_Fax {
            get {
                return this.contact_FaxField;
            }
            set {
                this.contact_FaxField = value;
            }
        }
        
        /// <remarks/>
        public string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customercontact")]
    public enum Marketing_Pref {
        
        /// <remarks/>
        Fax,
        
        /// <remarks/>
        _E_Mail,
        
        /// <remarks/>
        _No_Ads,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="1234", Namespace="urn:microsoft-dynamics-schemas/page/customercontact")]
    public enum Item1234 {
        
        /// <remarks/>
        _x0031_,
        
        /// <remarks/>
        _x0032_,
        
        /// <remarks/>
        _x0033_,
        
        /// <remarks/>
        _x0034_,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customercontact")]
    public enum Title {
        
        /// <remarks/>
        End_User,
        
        /// <remarks/>
        CC_End_User,
        
        /// <remarks/>
        Purchasing_Agent,
        
        /// <remarks/>
        Group_Team_Ldr_CMDR,
        
        /// <remarks/>
        Lab_Mgr_Supv,
        
        /// <remarks/>
        Secretary,
        
        /// <remarks/>
        Equip_Buyer,
        
        /// <remarks/>
        Safety_Off_1st_Rspndr,
        
        /// <remarks/>
        Supply_Logistics,
        
        /// <remarks/>
        Equip_Service_Engineer,
        
        /// <remarks/>
        Accounting,
        
        /// <remarks/>
        No_Longer_There,
        
        /// <remarks/>
        Whse_Rcvg,
        
        /// <remarks/>
        Small_Bus_Admin,
        
        /// <remarks/>
        Contracting_Officer,
        
        /// <remarks/>
        Advisor_Coord_Trainer,
        
        /// <remarks/>
        Director_Owner,
        
        /// <remarks/>
        Reseller,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customercontact")]
    public enum Lab_Type {
        
        /// <remarks/>
        Clinical_Medical,
        
        /// <remarks/>
        Water__x0026__Sewage,
        
        /// <remarks/>
        Forensic_Patho_Chem,
        
        /// <remarks/>
        Life_Clinical_Chem,
        
        /// <remarks/>
        Life_Chem,
        
        /// <remarks/>
        Earth_Energy__x0026__Fuel,
        
        /// <remarks/>
        Pharmaceutical,
        
        /// <remarks/>
        EnviroAnalytical,
        
        /// <remarks/>
        Life_Biology,
        
        /// <remarks/>
        Manufacturing,
        
        /// <remarks/>
        Life_BioEnviro_Chem,
        
        /// <remarks/>
        Life_Forensic_Chem,
        
        /// <remarks/>
        EMT_Fire__x0026__Safety,
        
        /// <remarks/>
        HLS__x0026__WMD,
        
        /// <remarks/>
        Industrial__x0026__Commercial,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customercontact")]
    public enum Discipline {
        
        /// <remarks/>
        General_Biology,
        
        /// <remarks/>
        Chromatography,
        
        /// <remarks/>
        Clinical_Chemistry_Respiratory,
        
        /// <remarks/>
        Life_Science_Unknown,
        
        /// <remarks/>
        Animal_Testing_Exp_Biology,
        
        /// <remarks/>
        Hematology,
        
        /// <remarks/>
        Histology_Cytology_Morgue,
        
        /// <remarks/>
        Microbiology__x0026__Fungi,
        
        /// <remarks/>
        Phlebotomy_Serology_Clinical_Diag,
        
        /// <remarks/>
        Other_Analytical_Chemistry,
        
        /// <remarks/>
        Water_Testing_pH_DO_ISE,
        
        /// <remarks/>
        Blood_Bank,
        
        /// <remarks/>
        BioEnviro_Ind_Hygiene,
        
        /// <remarks/>
        Hazmat_Safety_Security_WMD,
        
        /// <remarks/>
        DNA_RNA_PCR__x0026__MolecularBio,
        
        /// <remarks/>
        Peptides_Proteins__x0026__Biochemistry,
        
        /// <remarks/>
        Immunology_Virology_Nursing_Infection_Cntrl,
        
        /// <remarks/>
        Cell__x0026__Tissue_Culture,
        
        /// <remarks/>
        Genonmics__x0026__Proteomics,
        
        /// <remarks/>
        Cell_Signaling__x0026__Neuroscience,
        
        /// <remarks/>
        Automation_HTS_Robotics,
        
        /// <remarks/>
        Industrial__x0026__Commercial,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customercontact")]
    public partial class CustomerContact_Filter {
        
        private CustomerContact_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        public CustomerContact_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customercontact")]
    public enum CustomerContact_Fields {
        
        /// <remarks/>
        Sell_to_Customer_No,
        
        /// <remarks/>
        Contact_ID,
        
        /// <remarks/>
        Prefix,
        
        /// <remarks/>
        First_Name,
        
        /// <remarks/>
        Middle_Name,
        
        /// <remarks/>
        Last_Name,
        
        /// <remarks/>
        Suffix,
        
        /// <remarks/>
        Contact_Name,
        
        /// <remarks/>
        Calendars,
        
        /// <remarks/>
        Unsubscribe,
        
        /// <remarks/>
        Con_Sent,
        
        /// <remarks/>
        Marketing_Pref,
        
        /// <remarks/>
        _x0031_234,
        
        /// <remarks/>
        Building,
        
        /// <remarks/>
        Room_x0023_,
        
        /// <remarks/>
        US_Area_Code,
        
        /// <remarks/>
        Phone_Prefix,
        
        /// <remarks/>
        Number,
        
        /// <remarks/>
        Extension,
        
        /// <remarks/>
        International_Phone_Number,
        
        /// <remarks/>
        FAX_Area_Code,
        
        /// <remarks/>
        FAX_Prefix,
        
        /// <remarks/>
        FAX_Number,
        
        /// <remarks/>
        Title,
        
        /// <remarks/>
        Lab_Type,
        
        /// <remarks/>
        Discipline,
        
        /// <remarks/>
        Contact_E_Mail,
        
        /// <remarks/>
        Contact_Comments,
        
        /// <remarks/>
        Notes,
        
        /// <remarks/>
        MKTG_Address,
        
        /// <remarks/>
        City,
        
        /// <remarks/>
        State,
        
        /// <remarks/>
        zip,
        
        /// <remarks/>
        Contact_Phone,
        
        /// <remarks/>
        Contact_Fax,
        
        /// <remarks/>
        Color,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ReadCompletedEventHandler(object sender, ReadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerContact Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerContact)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ReadByRecIdCompletedEventHandler(object sender, ReadByRecIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadByRecIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadByRecIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerContact Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerContact)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ReadMultipleCompletedEventHandler(object sender, ReadMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerContact[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerContact[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void IsUpdatedCompletedEventHandler(object sender, IsUpdatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUpdatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsUpdatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetRecIdFromKeyCompletedEventHandler(object sender, GetRecIdFromKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecIdFromKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecIdFromKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CreateCompletedEventHandler(object sender, CreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerContact CustomerContact {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerContact)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CreateMultipleCompletedEventHandler(object sender, CreateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerContact[] CustomerContact_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerContact[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerContact CustomerContact {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerContact)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void UpdateMultipleCompletedEventHandler(object sender, UpdateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerContact[] CustomerContact_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerContact[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void DeleteCompletedEventHandler(object sender, DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591