//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizTalkLibrary.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.25.81:7047/DynamicsNAV90/WS/Government%20Scientific%20Source/Page/I" +
            "temCard")]
        public string BizTalkLibrary_ItemCard_ItemCard_Service {
            get {
                return ((string)(this["BizTalkLibrary_ItemCard_ItemCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.25.81:7047/DynamicsNAV90/WS/Government%20Scientific%20Source/Page/S" +
            "hipToAddress")]
        public string BizTalkLibrary_ShipToAddress_ShipToAddress_Service {
            get {
                return ((string)(this["BizTalkLibrary_ShipToAddress_ShipToAddress_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.25.81:7047/DynamicsNAV90/WS/Government%20Scientific%20Source/Page/C" +
            "ustomerContact")]
        public string BizTalkLibrary_CustomerCard_CustomerContact_Service {
            get {
                return ((string)(this["BizTalkLibrary_CustomerCard_CustomerContact_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.25.81:7047/DynamicsNAV90/WS/Government%20Scientific%20Source/Page/C" +
            "ustomerCreditCards")]
        public string BizTalkLibrary_TstCustomerCreditCards_CustomerCreditCards_Service {
            get {
                return ((string)(this["BizTalkLibrary_TstCustomerCreditCards_CustomerCreditCards_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.25.81:7047/DynamicsNAV90/WS/Government%20Scientific%20Source/Page/S" +
            "alesOrder")]
        public string BizTalkLibrary_TstSalesOrders_SalesOrder_Service {
            get {
                return ((string)(this["BizTalkLibrary_TstSalesOrders_SalesOrder_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.25.81:7047/DynamicsNAV90/WS/Government%20Scientific%20Source/Page/P" +
            "urchaseOrder")]
        public string BizTalkLibrary_PurchaseOrder_PurchaseOrder_Service {
            get {
                return ((string)(this["BizTalkLibrary_PurchaseOrder_PurchaseOrder_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.25.81:7047/DynamicsNAV90/WS/Government%20Scientific%20Source/Codeun" +
            "it/AutoPostDocument")]
        public string BizTalkLibrary_AutoPostDoc_AutoPostDocument {
            get {
                return ((string)(this["BizTalkLibrary_AutoPostDoc_AutoPostDocument"]));
            }
        }
    }
}
