//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BizTalkLibrary.WS_ItemCard {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ItemCard_Binding", Namespace="urn:microsoft-dynamics-schemas/page/itemcard")]
    public partial class ItemCard_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadByRecIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsUpdatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecIdFromKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback Delete_PPG_Bucket_List_CardOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ItemCard_Service() {
            this.Url = global::BizTalkLibrary.Properties.Settings.Default.BizTalkLibrary_ItemCard_ItemCard_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReadCompletedEventHandler ReadCompleted;
        
        /// <remarks/>
        public event ReadByRecIdCompletedEventHandler ReadByRecIdCompleted;
        
        /// <remarks/>
        public event ReadMultipleCompletedEventHandler ReadMultipleCompleted;
        
        /// <remarks/>
        public event IsUpdatedCompletedEventHandler IsUpdatedCompleted;
        
        /// <remarks/>
        public event GetRecIdFromKeyCompletedEventHandler GetRecIdFromKeyCompleted;
        
        /// <remarks/>
        public event CreateCompletedEventHandler CreateCompleted;
        
        /// <remarks/>
        public event CreateMultipleCompletedEventHandler CreateMultipleCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event UpdateMultipleCompletedEventHandler UpdateMultipleCompleted;
        
        /// <remarks/>
        public event DeleteCompletedEventHandler DeleteCompleted;
        
        /// <remarks/>
        public event Delete_PPG_Bucket_List_CardCompletedEventHandler Delete_PPG_Bucket_List_CardCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/itemcard:Read", RequestNamespace="urn:microsoft-dynamics-schemas/page/itemcard", ResponseElementName="Read_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/itemcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ItemCard")]
        public ItemCard Read(string No) {
            object[] results = this.Invoke("Read", new object[] {
                        No});
            return ((ItemCard)(results[0]));
        }
        
        /// <remarks/>
        public void ReadAsync(string No) {
            this.ReadAsync(No, null);
        }
        
        /// <remarks/>
        public void ReadAsync(string No, object userState) {
            if ((this.ReadOperationCompleted == null)) {
                this.ReadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadOperationCompleted);
            }
            this.InvokeAsync("Read", new object[] {
                        No}, this.ReadOperationCompleted, userState);
        }
        
        private void OnReadOperationCompleted(object arg) {
            if ((this.ReadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadCompleted(this, new ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/itemcard:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/itemcard", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/itemcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ItemCard")]
        public ItemCard ReadByRecId(string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        recId});
            return ((ItemCard)(results[0]));
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId) {
            this.ReadByRecIdAsync(recId, null);
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId, object userState) {
            if ((this.ReadByRecIdOperationCompleted == null)) {
                this.ReadByRecIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadByRecIdOperationCompleted);
            }
            this.InvokeAsync("ReadByRecId", new object[] {
                        recId}, this.ReadByRecIdOperationCompleted, userState);
        }
        
        private void OnReadByRecIdOperationCompleted(object arg) {
            if ((this.ReadByRecIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadByRecIdCompleted(this, new ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/itemcard:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/itemcard", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/itemcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ItemCard[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] ItemCard_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((ItemCard[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(ItemCard_Filter[] filter, string bookmarkKey, int setSize) {
            this.ReadMultipleAsync(filter, bookmarkKey, setSize, null);
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(ItemCard_Filter[] filter, string bookmarkKey, int setSize, object userState) {
            if ((this.ReadMultipleOperationCompleted == null)) {
                this.ReadMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadMultipleOperationCompleted);
            }
            this.InvokeAsync("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, this.ReadMultipleOperationCompleted, userState);
        }
        
        private void OnReadMultipleOperationCompleted(object arg) {
            if ((this.ReadMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadMultipleCompleted(this, new ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/itemcard:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/itemcard", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/itemcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key) {
            this.IsUpdatedAsync(Key, null);
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key, object userState) {
            if ((this.IsUpdatedOperationCompleted == null)) {
                this.IsUpdatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUpdatedOperationCompleted);
            }
            this.InvokeAsync("IsUpdated", new object[] {
                        Key}, this.IsUpdatedOperationCompleted, userState);
        }
        
        private void OnIsUpdatedOperationCompleted(object arg) {
            if ((this.IsUpdatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUpdatedCompleted(this, new IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/itemcard:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/itemcard", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/itemcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key) {
            this.GetRecIdFromKeyAsync(Key, null);
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key, object userState) {
            if ((this.GetRecIdFromKeyOperationCompleted == null)) {
                this.GetRecIdFromKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecIdFromKeyOperationCompleted);
            }
            this.InvokeAsync("GetRecIdFromKey", new object[] {
                        Key}, this.GetRecIdFromKeyOperationCompleted, userState);
        }
        
        private void OnGetRecIdFromKeyOperationCompleted(object arg) {
            if ((this.GetRecIdFromKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecIdFromKeyCompleted(this, new GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/itemcard:Create", RequestNamespace="urn:microsoft-dynamics-schemas/page/itemcard", ResponseElementName="Create_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/itemcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Create(ref ItemCard ItemCard) {
            object[] results = this.Invoke("Create", new object[] {
                        ItemCard});
            ItemCard = ((ItemCard)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAsync(ItemCard ItemCard) {
            this.CreateAsync(ItemCard, null);
        }
        
        /// <remarks/>
        public void CreateAsync(ItemCard ItemCard, object userState) {
            if ((this.CreateOperationCompleted == null)) {
                this.CreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOperationCompleted);
            }
            this.InvokeAsync("Create", new object[] {
                        ItemCard}, this.CreateOperationCompleted, userState);
        }
        
        private void OnCreateOperationCompleted(object arg) {
            if ((this.CreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCompleted(this, new CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/itemcard:CreateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/itemcard", ResponseElementName="CreateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/itemcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref ItemCard[] ItemCard_List) {
            object[] results = this.Invoke("CreateMultiple", new object[] {
                        ItemCard_List});
            ItemCard_List = ((ItemCard[])(results[0]));
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(ItemCard[] ItemCard_List) {
            this.CreateMultipleAsync(ItemCard_List, null);
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(ItemCard[] ItemCard_List, object userState) {
            if ((this.CreateMultipleOperationCompleted == null)) {
                this.CreateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateMultipleOperationCompleted);
            }
            this.InvokeAsync("CreateMultiple", new object[] {
                        ItemCard_List}, this.CreateMultipleOperationCompleted, userState);
        }
        
        private void OnCreateMultipleOperationCompleted(object arg) {
            if ((this.CreateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateMultipleCompleted(this, new CreateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/itemcard:Update", RequestNamespace="urn:microsoft-dynamics-schemas/page/itemcard", ResponseElementName="Update_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/itemcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(ref ItemCard ItemCard) {
            object[] results = this.Invoke("Update", new object[] {
                        ItemCard});
            ItemCard = ((ItemCard)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(ItemCard ItemCard) {
            this.UpdateAsync(ItemCard, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(ItemCard ItemCard, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        ItemCard}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/itemcard:UpdateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/itemcard", ResponseElementName="UpdateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/itemcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref ItemCard[] ItemCard_List) {
            object[] results = this.Invoke("UpdateMultiple", new object[] {
                        ItemCard_List});
            ItemCard_List = ((ItemCard[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(ItemCard[] ItemCard_List) {
            this.UpdateMultipleAsync(ItemCard_List, null);
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(ItemCard[] ItemCard_List, object userState) {
            if ((this.UpdateMultipleOperationCompleted == null)) {
                this.UpdateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMultipleOperationCompleted);
            }
            this.InvokeAsync("UpdateMultiple", new object[] {
                        ItemCard_List}, this.UpdateMultipleOperationCompleted, userState);
        }
        
        private void OnUpdateMultipleOperationCompleted(object arg) {
            if ((this.UpdateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMultipleCompleted(this, new UpdateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/itemcard:Delete", RequestNamespace="urn:microsoft-dynamics-schemas/page/itemcard", ResponseElementName="Delete_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/itemcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Result")]
        public bool Delete(string Key) {
            object[] results = this.Invoke("Delete", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAsync(string Key) {
            this.DeleteAsync(Key, null);
        }
        
        /// <remarks/>
        public void DeleteAsync(string Key, object userState) {
            if ((this.DeleteOperationCompleted == null)) {
                this.DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOperationCompleted);
            }
            this.InvokeAsync("Delete", new object[] {
                        Key}, this.DeleteOperationCompleted, userState);
        }
        
        private void OnDeleteOperationCompleted(object arg) {
            if ((this.DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/itemcard:Delete_PPG_Bucket_List_Card", RequestNamespace="urn:microsoft-dynamics-schemas/page/itemcard", ResponseElementName="Delete_PPG_Bucket_List_Card_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/itemcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_PPG_Bucket_List_Card_Result")]
        public bool Delete_PPG_Bucket_List_Card(string PPG_Bucket_List_Card_Key) {
            object[] results = this.Invoke("Delete_PPG_Bucket_List_Card", new object[] {
                        PPG_Bucket_List_Card_Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Delete_PPG_Bucket_List_CardAsync(string PPG_Bucket_List_Card_Key) {
            this.Delete_PPG_Bucket_List_CardAsync(PPG_Bucket_List_Card_Key, null);
        }
        
        /// <remarks/>
        public void Delete_PPG_Bucket_List_CardAsync(string PPG_Bucket_List_Card_Key, object userState) {
            if ((this.Delete_PPG_Bucket_List_CardOperationCompleted == null)) {
                this.Delete_PPG_Bucket_List_CardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_PPG_Bucket_List_CardOperationCompleted);
            }
            this.InvokeAsync("Delete_PPG_Bucket_List_Card", new object[] {
                        PPG_Bucket_List_Card_Key}, this.Delete_PPG_Bucket_List_CardOperationCompleted, userState);
        }
        
        private void OnDelete_PPG_Bucket_List_CardOperationCompleted(object arg) {
            if ((this.Delete_PPG_Bucket_List_CardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Delete_PPG_Bucket_List_CardCompleted(this, new Delete_PPG_Bucket_List_CardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcard")]
    public partial class ItemCard {
        
        private string keyField;
        
        private string noField;
        
        private string descriptionField;
        
        private string description_2Field;
        
        private string base_Unit_of_MeasureField;
        
        private decimal items_Per_UOMField;
        
        private bool items_Per_UOMFieldSpecified;
        
        private System.DateTime price_Updated_OnField;
        
        private bool price_Updated_OnFieldSpecified;
        
        private System.DateTime price_Valid_UntilField;
        
        private bool price_Valid_UntilFieldSpecified;
        
        private string noteField;
        
        private string extended_DescriptionField;
        
        private string uNSPSC_CodeField;
        
        private string picture_FileField;
        
        private decimal inventoryField;
        
        private bool inventoryFieldSpecified;
        
        private decimal qty_on_Purch_OrderField;
        
        private bool qty_on_Purch_OrderFieldSpecified;
        
        private decimal qty_on_Sales_OrderField;
        
        private bool qty_on_Sales_OrderFieldSpecified;
        
        private decimal qty_on_Purch_ReturnField;
        
        private bool qty_on_Purch_ReturnFieldSpecified;
        
        private decimal qty_on_Sales_ReturnField;
        
        private bool qty_on_Sales_ReturnFieldSpecified;
        
        private string gen_Prod_Posting_Group_2Field;
        
        private string inventory_Posting_Group_2Field;
        
        private string tax_Group_Code_2Field;
        
        private bool controlled_SubstanceField;
        
        private bool controlled_SubstanceFieldSpecified;
        
        private bool tempField;
        
        private bool tempFieldSpecified;
        
        private bool blockedField;
        
        private bool blockedFieldSpecified;
        
        private bool drop_Ship_OnlyField;
        
        private bool drop_Ship_OnlyFieldSpecified;
        
        private System.DateTime start_DateField;
        
        private bool start_DateFieldSpecified;
        
        private System.DateTime end_DateField;
        
        private bool end_DateFieldSpecified;
        
        private bool use_Standard_Nav_PricingField;
        
        private bool use_Standard_Nav_PricingFieldSpecified;
        
        private decimal standard_CostField;
        
        private bool standard_CostFieldSpecified;
        
        private decimal unit_PriceField;
        
        private bool unit_PriceFieldSpecified;
        
        private decimal gSS_List_PriceField;
        
        private bool gSS_List_PriceFieldSpecified;
        
        private decimal manufacturer_List_PriceField;
        
        private bool manufacturer_List_PriceFieldSpecified;
        
        private decimal _1_Standard_Cost_Unit_Price_0_0000001_100Field;
        
        private bool _1_Standard_Cost_Unit_Price_0_0000001_100FieldSpecified;
        
        private decimal last_Direct_CostField;
        
        private bool last_Direct_CostFieldSpecified;
        
        private decimal min_Sales_PriceField;
        
        private bool min_Sales_PriceFieldSpecified;
        
        private decimal lIDS_Price_NewField;
        
        private bool lIDS_Price_NewFieldSpecified;
        
        private decimal dAPA_PriceField;
        
        private bool dAPA_PriceFieldSpecified;
        
        private decimal eVA_PricingField;
        
        private bool eVA_PricingFieldSpecified;
        
        private decimal landed_CostField;
        
        private bool landed_CostFieldSpecified;
        
        private decimal recommended_Sales_PriceField;
        
        private bool recommended_Sales_PriceFieldSpecified;
        
        private string product_Group_CodeField;
        
        private decimal new_FSS_PriceField;
        
        private bool new_FSS_PriceFieldSpecified;
        
        private decimal new_STL_PriceField;
        
        private bool new_STL_PriceFieldSpecified;
        
        private string new_Contract_NoField;
        
        private string new_FSS_Sin_NoField;
        
        private System.DateTime most_Recent_Mod_Approval_DateField;
        
        private bool most_Recent_Mod_Approval_DateFieldSpecified;
        
        private string lA_CodeField;
        
        private string lA_Code_AdjustedField;
        
        private bool cost_is_AdjustedField;
        
        private bool cost_is_AdjustedFieldSpecified;
        
        private Replenishment_System replenishment_SystemField;
        
        private bool replenishment_SystemFieldSpecified;
        
        private string lead_Time_CalculationField;
        
        private string vendor_NoField;
        
        private string vendor_Item_NoField;
        
        private string purch_Unit_of_MeasureField;
        
        private System.DateTime last_Date_ModifiedField;
        
        private bool last_Date_ModifiedFieldSpecified;
        
        private Reordering_Policy reordering_PolicyField;
        
        private bool reordering_PolicyFieldSpecified;
        
        private bool include_InventoryField;
        
        private bool include_InventoryFieldSpecified;
        
        private bool stockkeeping_Unit_ExistsField;
        
        private bool stockkeeping_Unit_ExistsFieldSpecified;
        
        private decimal positive_Adjmt_QtyField;
        
        private bool positive_Adjmt_QtyFieldSpecified;
        
        private decimal negative_Adjmt_QtyField;
        
        private bool negative_Adjmt_QtyFieldSpecified;
        
        private decimal purchases_QtyField;
        
        private bool purchases_QtyFieldSpecified;
        
        private decimal sales_QtyField;
        
        private bool sales_QtyFieldSpecified;
        
        private string max_Shelf_LifeField;
        
        private decimal maximum_InventoryField;
        
        private bool maximum_InventoryFieldSpecified;
        
        private decimal reorder_PointField;
        
        private bool reorder_PointFieldSpecified;
        
        private decimal reorder_QuantityField;
        
        private bool reorder_QuantityFieldSpecified;
        
        private decimal maximum_Order_QuantityField;
        
        private bool maximum_Order_QuantityFieldSpecified;
        
        private decimal minimum_Order_QuantityField;
        
        private bool minimum_Order_QuantityFieldSpecified;
        
        private decimal order_MultipleField;
        
        private bool order_MultipleFieldSpecified;
        
        private decimal unit_CostField;
        
        private bool unit_CostFieldSpecified;
        
        private string country_Region_of_Origin_CodeField;
        
        private string phys_Invt_Counting_Period_CodeField;
        
        private System.DateTime last_Phys_Invt_DateField;
        
        private bool last_Phys_Invt_DateFieldSpecified;
        
        private System.DateTime last_Counting_Period_UpdateField;
        
        private bool last_Counting_Period_UpdateFieldSpecified;
        
        private System.DateTime next_Counting_Start_DateField;
        
        private bool next_Counting_Start_DateFieldSpecified;
        
        private System.DateTime next_Counting_End_DateField;
        
        private bool next_Counting_End_DateFieldSpecified;
        
        private string item_Tracking_CodeField;
        
        private string item_Category_CodeField;
        
        private System.DateTime date_AddedField;
        
        private bool date_AddedFieldSpecified;
        
        private string added_ByField;
        
        private bool automatic_Ext_TextsField;
        
        private bool automatic_Ext_TextsFieldSpecified;
        
        private string alternative_Item_NoField;
        
        private string gTINField;
        
        private PPG_Bucket_List_Card[] pPG_Bucket_List_CardField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Description_2 {
            get {
                return this.description_2Field;
            }
            set {
                this.description_2Field = value;
            }
        }
        
        /// <remarks/>
        public string Base_Unit_of_Measure {
            get {
                return this.base_Unit_of_MeasureField;
            }
            set {
                this.base_Unit_of_MeasureField = value;
            }
        }
        
        /// <remarks/>
        public decimal Items_Per_UOM {
            get {
                return this.items_Per_UOMField;
            }
            set {
                this.items_Per_UOMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Items_Per_UOMSpecified {
            get {
                return this.items_Per_UOMFieldSpecified;
            }
            set {
                this.items_Per_UOMFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Price_Updated_On {
            get {
                return this.price_Updated_OnField;
            }
            set {
                this.price_Updated_OnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Price_Updated_OnSpecified {
            get {
                return this.price_Updated_OnFieldSpecified;
            }
            set {
                this.price_Updated_OnFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Price_Valid_Until {
            get {
                return this.price_Valid_UntilField;
            }
            set {
                this.price_Valid_UntilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Price_Valid_UntilSpecified {
            get {
                return this.price_Valid_UntilFieldSpecified;
            }
            set {
                this.price_Valid_UntilFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
            }
        }
        
        /// <remarks/>
        public string Extended_Description {
            get {
                return this.extended_DescriptionField;
            }
            set {
                this.extended_DescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string UNSPSC_Code {
            get {
                return this.uNSPSC_CodeField;
            }
            set {
                this.uNSPSC_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Picture_File {
            get {
                return this.picture_FileField;
            }
            set {
                this.picture_FileField = value;
            }
        }
        
        /// <remarks/>
        public decimal Inventory {
            get {
                return this.inventoryField;
            }
            set {
                this.inventoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InventorySpecified {
            get {
                return this.inventoryFieldSpecified;
            }
            set {
                this.inventoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Qty_on_Purch_Order {
            get {
                return this.qty_on_Purch_OrderField;
            }
            set {
                this.qty_on_Purch_OrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Qty_on_Purch_OrderSpecified {
            get {
                return this.qty_on_Purch_OrderFieldSpecified;
            }
            set {
                this.qty_on_Purch_OrderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Qty_on_Sales_Order {
            get {
                return this.qty_on_Sales_OrderField;
            }
            set {
                this.qty_on_Sales_OrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Qty_on_Sales_OrderSpecified {
            get {
                return this.qty_on_Sales_OrderFieldSpecified;
            }
            set {
                this.qty_on_Sales_OrderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Qty_on_Purch_Return {
            get {
                return this.qty_on_Purch_ReturnField;
            }
            set {
                this.qty_on_Purch_ReturnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Qty_on_Purch_ReturnSpecified {
            get {
                return this.qty_on_Purch_ReturnFieldSpecified;
            }
            set {
                this.qty_on_Purch_ReturnFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Qty_on_Sales_Return {
            get {
                return this.qty_on_Sales_ReturnField;
            }
            set {
                this.qty_on_Sales_ReturnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Qty_on_Sales_ReturnSpecified {
            get {
                return this.qty_on_Sales_ReturnFieldSpecified;
            }
            set {
                this.qty_on_Sales_ReturnFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Gen_Prod_Posting_Group_2 {
            get {
                return this.gen_Prod_Posting_Group_2Field;
            }
            set {
                this.gen_Prod_Posting_Group_2Field = value;
            }
        }
        
        /// <remarks/>
        public string Inventory_Posting_Group_2 {
            get {
                return this.inventory_Posting_Group_2Field;
            }
            set {
                this.inventory_Posting_Group_2Field = value;
            }
        }
        
        /// <remarks/>
        public string Tax_Group_Code_2 {
            get {
                return this.tax_Group_Code_2Field;
            }
            set {
                this.tax_Group_Code_2Field = value;
            }
        }
        
        /// <remarks/>
        public bool Controlled_Substance {
            get {
                return this.controlled_SubstanceField;
            }
            set {
                this.controlled_SubstanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Controlled_SubstanceSpecified {
            get {
                return this.controlled_SubstanceFieldSpecified;
            }
            set {
                this.controlled_SubstanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool temp {
            get {
                return this.tempField;
            }
            set {
                this.tempField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tempSpecified {
            get {
                return this.tempFieldSpecified;
            }
            set {
                this.tempFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Blocked {
            get {
                return this.blockedField;
            }
            set {
                this.blockedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BlockedSpecified {
            get {
                return this.blockedFieldSpecified;
            }
            set {
                this.blockedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Drop_Ship_Only {
            get {
                return this.drop_Ship_OnlyField;
            }
            set {
                this.drop_Ship_OnlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Drop_Ship_OnlySpecified {
            get {
                return this.drop_Ship_OnlyFieldSpecified;
            }
            set {
                this.drop_Ship_OnlyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Start_Date {
            get {
                return this.start_DateField;
            }
            set {
                this.start_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Start_DateSpecified {
            get {
                return this.start_DateFieldSpecified;
            }
            set {
                this.start_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime End_Date {
            get {
                return this.end_DateField;
            }
            set {
                this.end_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool End_DateSpecified {
            get {
                return this.end_DateFieldSpecified;
            }
            set {
                this.end_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Use_Standard_Nav_Pricing {
            get {
                return this.use_Standard_Nav_PricingField;
            }
            set {
                this.use_Standard_Nav_PricingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Use_Standard_Nav_PricingSpecified {
            get {
                return this.use_Standard_Nav_PricingFieldSpecified;
            }
            set {
                this.use_Standard_Nav_PricingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Standard_Cost {
            get {
                return this.standard_CostField;
            }
            set {
                this.standard_CostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Standard_CostSpecified {
            get {
                return this.standard_CostFieldSpecified;
            }
            set {
                this.standard_CostFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Unit_Price {
            get {
                return this.unit_PriceField;
            }
            set {
                this.unit_PriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Unit_PriceSpecified {
            get {
                return this.unit_PriceFieldSpecified;
            }
            set {
                this.unit_PriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal GSS_List_Price {
            get {
                return this.gSS_List_PriceField;
            }
            set {
                this.gSS_List_PriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GSS_List_PriceSpecified {
            get {
                return this.gSS_List_PriceFieldSpecified;
            }
            set {
                this.gSS_List_PriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Manufacturer_List_Price {
            get {
                return this.manufacturer_List_PriceField;
            }
            set {
                this.manufacturer_List_PriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Manufacturer_List_PriceSpecified {
            get {
                return this.manufacturer_List_PriceFieldSpecified;
            }
            set {
                this.manufacturer_List_PriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_1_Standard_Cost_Unit_Price_+0_0000001_*100")]
        public decimal _1_Standard_Cost_Unit_Price_0_0000001_100 {
            get {
                return this._1_Standard_Cost_Unit_Price_0_0000001_100Field;
            }
            set {
                this._1_Standard_Cost_Unit_Price_0_0000001_100Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool _1_Standard_Cost_Unit_Price_0_0000001_100Specified {
            get {
                return this._1_Standard_Cost_Unit_Price_0_0000001_100FieldSpecified;
            }
            set {
                this._1_Standard_Cost_Unit_Price_0_0000001_100FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Last_Direct_Cost {
            get {
                return this.last_Direct_CostField;
            }
            set {
                this.last_Direct_CostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Last_Direct_CostSpecified {
            get {
                return this.last_Direct_CostFieldSpecified;
            }
            set {
                this.last_Direct_CostFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Min_Sales_Price {
            get {
                return this.min_Sales_PriceField;
            }
            set {
                this.min_Sales_PriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Min_Sales_PriceSpecified {
            get {
                return this.min_Sales_PriceFieldSpecified;
            }
            set {
                this.min_Sales_PriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal LIDS_Price_New {
            get {
                return this.lIDS_Price_NewField;
            }
            set {
                this.lIDS_Price_NewField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LIDS_Price_NewSpecified {
            get {
                return this.lIDS_Price_NewFieldSpecified;
            }
            set {
                this.lIDS_Price_NewFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal DAPA_Price {
            get {
                return this.dAPA_PriceField;
            }
            set {
                this.dAPA_PriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DAPA_PriceSpecified {
            get {
                return this.dAPA_PriceFieldSpecified;
            }
            set {
                this.dAPA_PriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal eVA_Pricing {
            get {
                return this.eVA_PricingField;
            }
            set {
                this.eVA_PricingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eVA_PricingSpecified {
            get {
                return this.eVA_PricingFieldSpecified;
            }
            set {
                this.eVA_PricingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Landed_Cost {
            get {
                return this.landed_CostField;
            }
            set {
                this.landed_CostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Landed_CostSpecified {
            get {
                return this.landed_CostFieldSpecified;
            }
            set {
                this.landed_CostFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Recommended_Sales_Price {
            get {
                return this.recommended_Sales_PriceField;
            }
            set {
                this.recommended_Sales_PriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Recommended_Sales_PriceSpecified {
            get {
                return this.recommended_Sales_PriceFieldSpecified;
            }
            set {
                this.recommended_Sales_PriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Product_Group_Code {
            get {
                return this.product_Group_CodeField;
            }
            set {
                this.product_Group_CodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal New_FSS_Price {
            get {
                return this.new_FSS_PriceField;
            }
            set {
                this.new_FSS_PriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool New_FSS_PriceSpecified {
            get {
                return this.new_FSS_PriceFieldSpecified;
            }
            set {
                this.new_FSS_PriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal New_STL_Price {
            get {
                return this.new_STL_PriceField;
            }
            set {
                this.new_STL_PriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool New_STL_PriceSpecified {
            get {
                return this.new_STL_PriceFieldSpecified;
            }
            set {
                this.new_STL_PriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string New_Contract_No {
            get {
                return this.new_Contract_NoField;
            }
            set {
                this.new_Contract_NoField = value;
            }
        }
        
        /// <remarks/>
        public string New_FSS_Sin_No {
            get {
                return this.new_FSS_Sin_NoField;
            }
            set {
                this.new_FSS_Sin_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Most_Recent_Mod_Approval_Date {
            get {
                return this.most_Recent_Mod_Approval_DateField;
            }
            set {
                this.most_Recent_Mod_Approval_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Most_Recent_Mod_Approval_DateSpecified {
            get {
                return this.most_Recent_Mod_Approval_DateFieldSpecified;
            }
            set {
                this.most_Recent_Mod_Approval_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string LA_Code {
            get {
                return this.lA_CodeField;
            }
            set {
                this.lA_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string LA_Code_Adjusted {
            get {
                return this.lA_Code_AdjustedField;
            }
            set {
                this.lA_Code_AdjustedField = value;
            }
        }
        
        /// <remarks/>
        public bool Cost_is_Adjusted {
            get {
                return this.cost_is_AdjustedField;
            }
            set {
                this.cost_is_AdjustedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Cost_is_AdjustedSpecified {
            get {
                return this.cost_is_AdjustedFieldSpecified;
            }
            set {
                this.cost_is_AdjustedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Replenishment_System Replenishment_System {
            get {
                return this.replenishment_SystemField;
            }
            set {
                this.replenishment_SystemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Replenishment_SystemSpecified {
            get {
                return this.replenishment_SystemFieldSpecified;
            }
            set {
                this.replenishment_SystemFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Lead_Time_Calculation {
            get {
                return this.lead_Time_CalculationField;
            }
            set {
                this.lead_Time_CalculationField = value;
            }
        }
        
        /// <remarks/>
        public string Vendor_No {
            get {
                return this.vendor_NoField;
            }
            set {
                this.vendor_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Vendor_Item_No {
            get {
                return this.vendor_Item_NoField;
            }
            set {
                this.vendor_Item_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Purch_Unit_of_Measure {
            get {
                return this.purch_Unit_of_MeasureField;
            }
            set {
                this.purch_Unit_of_MeasureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Last_Date_Modified {
            get {
                return this.last_Date_ModifiedField;
            }
            set {
                this.last_Date_ModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Last_Date_ModifiedSpecified {
            get {
                return this.last_Date_ModifiedFieldSpecified;
            }
            set {
                this.last_Date_ModifiedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Reordering_Policy Reordering_Policy {
            get {
                return this.reordering_PolicyField;
            }
            set {
                this.reordering_PolicyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Reordering_PolicySpecified {
            get {
                return this.reordering_PolicyFieldSpecified;
            }
            set {
                this.reordering_PolicyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Include_Inventory {
            get {
                return this.include_InventoryField;
            }
            set {
                this.include_InventoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Include_InventorySpecified {
            get {
                return this.include_InventoryFieldSpecified;
            }
            set {
                this.include_InventoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Stockkeeping_Unit_Exists {
            get {
                return this.stockkeeping_Unit_ExistsField;
            }
            set {
                this.stockkeeping_Unit_ExistsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Stockkeeping_Unit_ExistsSpecified {
            get {
                return this.stockkeeping_Unit_ExistsFieldSpecified;
            }
            set {
                this.stockkeeping_Unit_ExistsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Positive_Adjmt_Qty {
            get {
                return this.positive_Adjmt_QtyField;
            }
            set {
                this.positive_Adjmt_QtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Positive_Adjmt_QtySpecified {
            get {
                return this.positive_Adjmt_QtyFieldSpecified;
            }
            set {
                this.positive_Adjmt_QtyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Negative_Adjmt_Qty {
            get {
                return this.negative_Adjmt_QtyField;
            }
            set {
                this.negative_Adjmt_QtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Negative_Adjmt_QtySpecified {
            get {
                return this.negative_Adjmt_QtyFieldSpecified;
            }
            set {
                this.negative_Adjmt_QtyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Purchases_Qty {
            get {
                return this.purchases_QtyField;
            }
            set {
                this.purchases_QtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Purchases_QtySpecified {
            get {
                return this.purchases_QtyFieldSpecified;
            }
            set {
                this.purchases_QtyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Sales_Qty {
            get {
                return this.sales_QtyField;
            }
            set {
                this.sales_QtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Sales_QtySpecified {
            get {
                return this.sales_QtyFieldSpecified;
            }
            set {
                this.sales_QtyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Max_Shelf_Life {
            get {
                return this.max_Shelf_LifeField;
            }
            set {
                this.max_Shelf_LifeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Maximum_Inventory {
            get {
                return this.maximum_InventoryField;
            }
            set {
                this.maximum_InventoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Maximum_InventorySpecified {
            get {
                return this.maximum_InventoryFieldSpecified;
            }
            set {
                this.maximum_InventoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Reorder_Point {
            get {
                return this.reorder_PointField;
            }
            set {
                this.reorder_PointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Reorder_PointSpecified {
            get {
                return this.reorder_PointFieldSpecified;
            }
            set {
                this.reorder_PointFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Reorder_Quantity {
            get {
                return this.reorder_QuantityField;
            }
            set {
                this.reorder_QuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Reorder_QuantitySpecified {
            get {
                return this.reorder_QuantityFieldSpecified;
            }
            set {
                this.reorder_QuantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Maximum_Order_Quantity {
            get {
                return this.maximum_Order_QuantityField;
            }
            set {
                this.maximum_Order_QuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Maximum_Order_QuantitySpecified {
            get {
                return this.maximum_Order_QuantityFieldSpecified;
            }
            set {
                this.maximum_Order_QuantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Minimum_Order_Quantity {
            get {
                return this.minimum_Order_QuantityField;
            }
            set {
                this.minimum_Order_QuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Minimum_Order_QuantitySpecified {
            get {
                return this.minimum_Order_QuantityFieldSpecified;
            }
            set {
                this.minimum_Order_QuantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Order_Multiple {
            get {
                return this.order_MultipleField;
            }
            set {
                this.order_MultipleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Order_MultipleSpecified {
            get {
                return this.order_MultipleFieldSpecified;
            }
            set {
                this.order_MultipleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Unit_Cost {
            get {
                return this.unit_CostField;
            }
            set {
                this.unit_CostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Unit_CostSpecified {
            get {
                return this.unit_CostFieldSpecified;
            }
            set {
                this.unit_CostFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Country_Region_of_Origin_Code {
            get {
                return this.country_Region_of_Origin_CodeField;
            }
            set {
                this.country_Region_of_Origin_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Phys_Invt_Counting_Period_Code {
            get {
                return this.phys_Invt_Counting_Period_CodeField;
            }
            set {
                this.phys_Invt_Counting_Period_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Last_Phys_Invt_Date {
            get {
                return this.last_Phys_Invt_DateField;
            }
            set {
                this.last_Phys_Invt_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Last_Phys_Invt_DateSpecified {
            get {
                return this.last_Phys_Invt_DateFieldSpecified;
            }
            set {
                this.last_Phys_Invt_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Last_Counting_Period_Update {
            get {
                return this.last_Counting_Period_UpdateField;
            }
            set {
                this.last_Counting_Period_UpdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Last_Counting_Period_UpdateSpecified {
            get {
                return this.last_Counting_Period_UpdateFieldSpecified;
            }
            set {
                this.last_Counting_Period_UpdateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Next_Counting_Start_Date {
            get {
                return this.next_Counting_Start_DateField;
            }
            set {
                this.next_Counting_Start_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Next_Counting_Start_DateSpecified {
            get {
                return this.next_Counting_Start_DateFieldSpecified;
            }
            set {
                this.next_Counting_Start_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Next_Counting_End_Date {
            get {
                return this.next_Counting_End_DateField;
            }
            set {
                this.next_Counting_End_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Next_Counting_End_DateSpecified {
            get {
                return this.next_Counting_End_DateFieldSpecified;
            }
            set {
                this.next_Counting_End_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Item_Tracking_Code {
            get {
                return this.item_Tracking_CodeField;
            }
            set {
                this.item_Tracking_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Item_Category_Code {
            get {
                return this.item_Category_CodeField;
            }
            set {
                this.item_Category_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Date_Added {
            get {
                return this.date_AddedField;
            }
            set {
                this.date_AddedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Date_AddedSpecified {
            get {
                return this.date_AddedFieldSpecified;
            }
            set {
                this.date_AddedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Added_By {
            get {
                return this.added_ByField;
            }
            set {
                this.added_ByField = value;
            }
        }
        
        /// <remarks/>
        public bool Automatic_Ext_Texts {
            get {
                return this.automatic_Ext_TextsField;
            }
            set {
                this.automatic_Ext_TextsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Automatic_Ext_TextsSpecified {
            get {
                return this.automatic_Ext_TextsFieldSpecified;
            }
            set {
                this.automatic_Ext_TextsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Alternative_Item_No {
            get {
                return this.alternative_Item_NoField;
            }
            set {
                this.alternative_Item_NoField = value;
            }
        }
        
        /// <remarks/>
        public string GTIN {
            get {
                return this.gTINField;
            }
            set {
                this.gTINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public PPG_Bucket_List_Card[] PPG_Bucket_List_Card {
            get {
                return this.pPG_Bucket_List_CardField;
            }
            set {
                this.pPG_Bucket_List_CardField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcard")]
    public enum Replenishment_System {
        
        /// <remarks/>
        Purchase,
        
        /// <remarks/>
        Prod_Order,
        
        /// <remarks/>
        Assembly,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcard")]
    public enum Reordering_Policy {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Fixed_Reorder_Qty,
        
        /// <remarks/>
        Maximum_Qty,
        
        /// <remarks/>
        Order,
        
        /// <remarks/>
        Lot_for_Lot,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcard")]
    public partial class PPG_Bucket_List_Card {
        
        private string keyField;
        
        private string category1Field;
        
        private string category2Field;
        
        private string category3Field;
        
        private string category4Field;
        
        private string category5Field;
        
        private string category6Field;
        
        private string leafNodeField;
        
        private string category1TCField;
        
        private string category2TCField;
        
        private string category3TCField;
        
        private string category4TCField;
        
        private string category5TCField;
        
        private string category6TCField;
        
        private string leafNodeTCField;
        
        private string pPGField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Category1 {
            get {
                return this.category1Field;
            }
            set {
                this.category1Field = value;
            }
        }
        
        /// <remarks/>
        public string Category2 {
            get {
                return this.category2Field;
            }
            set {
                this.category2Field = value;
            }
        }
        
        /// <remarks/>
        public string Category3 {
            get {
                return this.category3Field;
            }
            set {
                this.category3Field = value;
            }
        }
        
        /// <remarks/>
        public string Category4 {
            get {
                return this.category4Field;
            }
            set {
                this.category4Field = value;
            }
        }
        
        /// <remarks/>
        public string Category5 {
            get {
                return this.category5Field;
            }
            set {
                this.category5Field = value;
            }
        }
        
        /// <remarks/>
        public string Category6 {
            get {
                return this.category6Field;
            }
            set {
                this.category6Field = value;
            }
        }
        
        /// <remarks/>
        public string LeafNode {
            get {
                return this.leafNodeField;
            }
            set {
                this.leafNodeField = value;
            }
        }
        
        /// <remarks/>
        public string Category1TC {
            get {
                return this.category1TCField;
            }
            set {
                this.category1TCField = value;
            }
        }
        
        /// <remarks/>
        public string Category2TC {
            get {
                return this.category2TCField;
            }
            set {
                this.category2TCField = value;
            }
        }
        
        /// <remarks/>
        public string Category3TC {
            get {
                return this.category3TCField;
            }
            set {
                this.category3TCField = value;
            }
        }
        
        /// <remarks/>
        public string Category4TC {
            get {
                return this.category4TCField;
            }
            set {
                this.category4TCField = value;
            }
        }
        
        /// <remarks/>
        public string Category5TC {
            get {
                return this.category5TCField;
            }
            set {
                this.category5TCField = value;
            }
        }
        
        /// <remarks/>
        public string Category6TC {
            get {
                return this.category6TCField;
            }
            set {
                this.category6TCField = value;
            }
        }
        
        /// <remarks/>
        public string LeafNodeTC {
            get {
                return this.leafNodeTCField;
            }
            set {
                this.leafNodeTCField = value;
            }
        }
        
        /// <remarks/>
        public string PPG {
            get {
                return this.pPGField;
            }
            set {
                this.pPGField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcard")]
    public partial class ItemCard_Filter {
        
        private ItemCard_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        public ItemCard_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcard")]
    public enum ItemCard_Fields {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Description,
        
        /// <remarks/>
        Description_2,
        
        /// <remarks/>
        Base_Unit_of_Measure,
        
        /// <remarks/>
        Items_Per_UOM,
        
        /// <remarks/>
        Price_Updated_On,
        
        /// <remarks/>
        Price_Valid_Until,
        
        /// <remarks/>
        Note,
        
        /// <remarks/>
        Extended_Description,
        
        /// <remarks/>
        UNSPSC_Code,
        
        /// <remarks/>
        Picture_File,
        
        /// <remarks/>
        Inventory,
        
        /// <remarks/>
        Qty_on_Purch_Order,
        
        /// <remarks/>
        Qty_on_Sales_Order,
        
        /// <remarks/>
        Qty_on_Purch_Return,
        
        /// <remarks/>
        Qty_on_Sales_Return,
        
        /// <remarks/>
        Gen_Prod_Posting_Group_2,
        
        /// <remarks/>
        Inventory_Posting_Group_2,
        
        /// <remarks/>
        Tax_Group_Code_2,
        
        /// <remarks/>
        Controlled_Substance,
        
        /// <remarks/>
        temp,
        
        /// <remarks/>
        Blocked,
        
        /// <remarks/>
        Drop_Ship_Only,
        
        /// <remarks/>
        Start_Date,
        
        /// <remarks/>
        End_Date,
        
        /// <remarks/>
        Use_Standard_Nav_Pricing,
        
        /// <remarks/>
        Standard_Cost,
        
        /// <remarks/>
        Unit_Price,
        
        /// <remarks/>
        GSS_List_Price,
        
        /// <remarks/>
        Manufacturer_List_Price,
        
        /// <remarks/>
        _1_Standard_Cost_Unit_Price__x002B_0_0000001__x002A_100,
        
        /// <remarks/>
        Last_Direct_Cost,
        
        /// <remarks/>
        Min_Sales_Price,
        
        /// <remarks/>
        LIDS_Price_New,
        
        /// <remarks/>
        DAPA_Price,
        
        /// <remarks/>
        eVA_Pricing,
        
        /// <remarks/>
        Landed_Cost,
        
        /// <remarks/>
        Recommended_Sales_Price,
        
        /// <remarks/>
        Product_Group_Code,
        
        /// <remarks/>
        New_FSS_Price,
        
        /// <remarks/>
        New_STL_Price,
        
        /// <remarks/>
        New_Contract_No,
        
        /// <remarks/>
        New_FSS_Sin_No,
        
        /// <remarks/>
        Most_Recent_Mod_Approval_Date,
        
        /// <remarks/>
        LA_Code,
        
        /// <remarks/>
        LA_Code_Adjusted,
        
        /// <remarks/>
        Cost_is_Adjusted,
        
        /// <remarks/>
        Replenishment_System,
        
        /// <remarks/>
        Lead_Time_Calculation,
        
        /// <remarks/>
        Vendor_No,
        
        /// <remarks/>
        Vendor_Item_No,
        
        /// <remarks/>
        Purch_Unit_of_Measure,
        
        /// <remarks/>
        Last_Date_Modified,
        
        /// <remarks/>
        Reordering_Policy,
        
        /// <remarks/>
        Include_Inventory,
        
        /// <remarks/>
        Stockkeeping_Unit_Exists,
        
        /// <remarks/>
        Positive_Adjmt_Qty,
        
        /// <remarks/>
        Negative_Adjmt_Qty,
        
        /// <remarks/>
        Purchases_Qty,
        
        /// <remarks/>
        Sales_Qty,
        
        /// <remarks/>
        Max_Shelf_Life,
        
        /// <remarks/>
        Maximum_Inventory,
        
        /// <remarks/>
        Reorder_Point,
        
        /// <remarks/>
        Reorder_Quantity,
        
        /// <remarks/>
        Maximum_Order_Quantity,
        
        /// <remarks/>
        Minimum_Order_Quantity,
        
        /// <remarks/>
        Order_Multiple,
        
        /// <remarks/>
        Unit_Cost,
        
        /// <remarks/>
        Country_Region_of_Origin_Code,
        
        /// <remarks/>
        Phys_Invt_Counting_Period_Code,
        
        /// <remarks/>
        Last_Phys_Invt_Date,
        
        /// <remarks/>
        Last_Counting_Period_Update,
        
        /// <remarks/>
        Next_Counting_Start_Date,
        
        /// <remarks/>
        Next_Counting_End_Date,
        
        /// <remarks/>
        Item_Tracking_Code,
        
        /// <remarks/>
        Item_Category_Code,
        
        /// <remarks/>
        Date_Added,
        
        /// <remarks/>
        Added_By,
        
        /// <remarks/>
        Automatic_Ext_Texts,
        
        /// <remarks/>
        Alternative_Item_No,
        
        /// <remarks/>
        GTIN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ReadCompletedEventHandler(object sender, ReadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ItemCard Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ItemCard)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ReadByRecIdCompletedEventHandler(object sender, ReadByRecIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadByRecIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadByRecIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ItemCard Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ItemCard)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ReadMultipleCompletedEventHandler(object sender, ReadMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ItemCard[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ItemCard[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void IsUpdatedCompletedEventHandler(object sender, IsUpdatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUpdatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsUpdatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetRecIdFromKeyCompletedEventHandler(object sender, GetRecIdFromKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecIdFromKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecIdFromKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CreateCompletedEventHandler(object sender, CreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ItemCard ItemCard {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ItemCard)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CreateMultipleCompletedEventHandler(object sender, CreateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ItemCard[] ItemCard_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ItemCard[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ItemCard ItemCard {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ItemCard)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void UpdateMultipleCompletedEventHandler(object sender, UpdateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ItemCard[] ItemCard_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ItemCard[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void DeleteCompletedEventHandler(object sender, DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Delete_PPG_Bucket_List_CardCompletedEventHandler(object sender, Delete_PPG_Bucket_List_CardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Delete_PPG_Bucket_List_CardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Delete_PPG_Bucket_List_CardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591